name: al_quran
description: "Al Quran App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  fluttertoast: ^8.2.8
  flutter_downloader: ^1.11.8
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.0
  tuple: ^2.0.2
  flutter_hooks: ^0.20.5
  from_css_color: ^2.0.0
  permission_handler: ^11.3.1
  device_info_plus: ^11.1.1
  http: ^1.2.2
  flutter_svg: ^2.0.14
  geolocator: ^13.0.1
  flutter_qiblah: ^3.0.4
  flutter_inappwebview: ^6.1.5
  just_audio: ^0.9.42
  scrollable_positioned_list: ^0.3.8
  dropdown_button2: ^2.3.9
  flutter_local_notifications: ^18.0.1
  adhan: ^2.0.0+1
  google_maps_flutter: ^2.10.0
  geocoding: ^3.0.0
  hijri: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.2
  change_app_package_name: ^1.4.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/images/light/
    - assets/images/dark/
    - assets/images/milk/
    - assets/images/blue/
    - assets/images/night/
    - assets/database/
    - assets/fonts/
    - assets/icon/
    - assets/js/

  fonts:
    - family: regularFont
      fonts:
        - asset: assets/fonts/regularFont.ttf

    - family: semiBoldFont
      fonts:
        - asset: assets/fonts/semiBoldFont.ttf

    - family: boldFont
      fonts:
        - asset: assets/fonts/boldFont.ttf

    - family: indopakFont
      fonts:
        - asset: assets/fonts/indopakFont.ttf


flutter_native_splash:
  color: "#dee3e6"
  color_dark: "#222324"
  image: assets/images/brand.png

  android_12:
    color: "#dee3e6"
    color_dark: "#222324"
    image: assets/images/brand.png


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/app_icon.png"